import sagas from './sagas';
import {
  createDocument,
  getDocument,
  getDocuments,
  uploadDocument,
  updateDocument,
  mergeTemplate,
  $mergeTemplate,
  replicateTemplate,
  $replicateTemplate,
  deleteDocuments,
  watchDocumentConvertionProgress,
  sendReminder,
  sendDocumentBulk,
  $sendDocumentBulk,
  cleanFileData,
  copyDocument,
  $cleanFileData,
  $sendReminder,
  $createDocument,
  $getDocument,
  $copyDocument,
  getAllDocuments,
  $getAllDocuments,
  $getDocuments,
  $uploadDocument,
  $updateDocument,
  $deleteDocuments,
  revertDocument,
  $revertDocument,
  getDocumentDownloadUrl,
  $getDocumentDownloadUrl,
  activateTemplate,
  $activateTemplate,
  getDocumentActivities,
  $getDocumentActivities,
  createDocumentFromFormRequest,
  $createDocumentFromFormRequest,
  removeTemplateFromApi,
  $removeTemplateFromApi,
  addTemplateToApi,
  $addTemplateToApi,
  getFormRequest,
  $getFormRequest,
  disableForm,
  $disableForm,
  enableForm,
  $enableForm,
  $toggleEmailNotification,
  toggleEmailNotification,
  $getAllTemplates,
  getAllTemplates,
} from './actionCreators';
import reducer from './reducer';

export default {
  sagas,
  reducer,
  actions: {
    createDocument,
    getDocument,
    sendReminder,
    getDocuments,
    uploadDocument,
    updateDocument,
    getAllDocuments,
    mergeTemplate,
    replicateTemplate,
    revertDocument,
    deleteDocuments,
    copyDocument,
    cleanFileData,
    getDocumentDownloadUrl,
    activateTemplate,
    sendDocumentBulk,
    watchDocumentConvertionProgress,
    getDocumentActivities,
    createDocumentFromFormRequest,
    removeTemplateFromApi,
    addTemplateToApi,
    getFormRequest,
    disableForm,
    enableForm,
    toggleEmailNotification,
    getAllTemplates,
  },
};

export const $actions = {
  createDocument: $createDocument,
  getDocument: $getDocument,
  getDocuments: $getDocuments,
  revertDocument: $revertDocument,
  mergeTemplate: $mergeTemplate,
  replicateTemplate: $replicateTemplate,
  sendReminder: $sendReminder,
  uploadDocument: $uploadDocument,
  updateDocument: $updateDocument,
  toggleEmailNotification: $toggleEmailNotification,
  sendDocumentBulk: $sendDocumentBulk,
  getAllDocuments: $getAllDocuments,
  copyDocument: $copyDocument,
  deleteDocuments: $deleteDocuments,
  cleanFileData: $cleanFileData,
  getDocumentDownloadUrl: $getDocumentDownloadUrl,
  activateTemplate: $activateTemplate,
  getDocumentActivities: $getDocumentActivities,
  createDocumentFromFormRequest: $createDocumentFromFormRequest,
  addTemplateToApi: $addTemplateToApi,
  removeTemplateFromApi: $removeTemplateFromApi,
  getFormRequest: $getFormRequest,
  disableForm: $disableForm,
  enableForm: $enableForm,
  getAllTemlates: $getAllTemplates,
};
