import {
  initDocumentSigning,
  finishDocumentSigning,
  getAvailableSignersOptions,
  $getAvailableSignersOptions,
  getSignerDocument,
  $getSignerDocument,
  submitSignedDocument,
  $submitSignedDocument,
  sendDocumentOut,
  $sendDocumentOut,
  sendReminders,
  $sendReminders,
  sendSignatoryOpened,
  $sendSignatoryOpened,
  getDocumentPreviewPages,
  $getDocumentPreviewPages,
  getDocumentShareUrl,
  $getDocumentShareUrl,
  shareDocument,
  $shareDocument,
  getDocumentConvertionStatus,
  $getDocumentConvertionStatus,
  $sendCodeAccess,
  $getSigningUrl,
  sendCodeAccess,
  getSigningUrl,
} from './actionCreators';
import sagas from './sagas';

export default {
  sagas,
  actions: {
    initDocumentSigning,
    finishDocumentSigning,
    getSignerDocument,
    submitSignedDocument,
    getAvailableSignersOptions,
    sendDocumentOut,
    sendReminders,
    sendSignatoryOpened,
    getDocumentPreviewPages,
    getDocumentShareUrl,
    shareDocument,
    getDocumentConvertionStatus,
    sendCodeAccess,
    getSigningUrl,
  },
};

export const $actions = {
  getSignerDocument: $getSignerDocument,
  submitSignedDocument: $submitSignedDocument,
  getAvailableSignersOptions: $getAvailableSignersOptions,
  sendDocumentOut: $sendDocumentOut,
  sendReminders: $sendReminders,
  sendSignatoryOpened: $sendSignatoryOpened,
  getDocumentPreviewPages: $getDocumentPreviewPages,
  getDocumentShareUrl: $getDocumentShareUrl,
  shareDocument: $shareDocument,
  getDocumentConvertionStatus: $getDocumentConvertionStatus,
  sendCodeAccess: $sendCodeAccess,
  getSigningUrl: $getSigningUrl,
};
